//! Tauri 命令集合。
pub mod ai;
pub mod file;
pub mod local;
pub mod local_shell;
pub mod profile;
pub mod proxy;
pub mod rdp;
pub mod remote_edit;
pub mod resource_monitor;
pub mod security;
pub mod serial;
pub mod sftp;
pub mod ssh;
pub mod system;
pub mod tunnel;
